### ISSUE TITLE
APIServer Instantiating ZK twice

### ISSUE THREAD

**Issue by datacrystals** [carboncopies/BrainGenix-UI#1]
The APIServer is starting everything twice, two BG motd messages, etc. Crashes with this error:

```INFO:     Uvicorn running on http://0.0.0.0:2001 (Press CTRL+C to quit)
INFO:     10.1.9.2:49026 - "GET / HTTP/1.1" 200 OK
[    2] [2021-05-16 21:26:04] [           Zookeeper] [      LeaderTimeout] Can't find Zookeeper Leader! No Quorum?
Exception in thread Zookeeper Leader Timeout Checker:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/BrainGenix-UI/back-end/Core/Internode/Zookeeper/Zookeeper.py", line 253, in LeaderCheckDaemon
    if (self.ZookeeperConnection.get('/BrainGenix/System/Leader')[0] != self.Name.encode() and (self.ZookeeperMode == 'Leader')):
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 1165, in get
    return self.get_async(path, watch=watch).get()
  File "/usr/local/lib/python3.8/dist-packages/kazoo/handlers/utils.py", line 75, in get
    raise self._exception
kazoo.exceptions.NoNodeError
[    2] [2021-05-16 21:26:04] [           Zookeeper] [      LeaderTimeout] Can't find Zookeeper Leader! No Quorum?
Exception in thread Zookeeper Leader Timeout Checker:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/BrainGenix-UI/back-end/Core/Internode/Zookeeper/Zookeeper.py", line 253, in LeaderCheckDaemon
    if (self.ZookeeperConnection.get('/BrainGenix/System/Leader')[0] != self.Name.encode() and (self.ZookeeperMode == 'Leader')):
  File "/usr/local/lib/python3.8/dist-packages/kazoo/client.py", line 1165, in get
    return self.get_async(path, watch=watch).get()
  File "/usr/local/lib/python3.8/dist-packages/kazoo/handlers/utils.py", line 75, in get
    raise self._exception
kazoo.exceptions.NoNodeError
```

**Comment by datacrystals** [comment]
Resolved with commit 47
